version: "3.9"
services:
  node-app:
    container_name: node-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOST=${HOST}
      - LOG_LEVEL=${LOG_LEVEL}
