version: "3.9"
services:
  node-app:
    container_name: node-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
